import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          '"Noto Sans"',
          'sans-serif',
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        serif: ['var(--font-serif)', 'ui-serif', 'Georgia', 'serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      letterSpacing: {
        tightish: '-0.01em',
        tighter2: '-0.02em',
      },
      colors: {
        canvas: 'var(--bg-canvas)',
        sidebar: 'var(--bg-sidebar)',
        input: 'var(--bg-input)',
        elevated: 'var(--bg-elevated)',
        'elevated-hover': 'var(--bg-elevated-hover)',
        code: 'var(--bg-code)',
        skeleton: 'var(--bg-skeleton)',
        primary: 'var(--text-primary)',
        secondary: 'var(--text-secondary)',
        muted: 'var(--text-muted)',
        inverse: 'var(--text-inverse)',
        borderSubtle: 'var(--border-subtle)',
        borderStrong: 'var(--border-strong)',
        borderFocus: 'var(--border-focus)',
        progressBg: 'var(--progress-bg)',
        progressBorder: 'var(--progress-border)',
        progressShadow: 'var(--progress-shadow)',
        dark: {
          50: '#f7f7f8',
          100: '#ececf1',
          200: '#d9d9e3',
          300: '#c5c5d2',
          400: '#acacbe',
          500: '#8e8ea0',
          600: '#6e6e80',
          700: '#4a4a5a',
          800: '#343541',
          850: '#2a2b36',
          900: '#202123',
          950: '#171719',
        },
        accent: {
          brand: 'var(--accent-brand)',
          'brand-hover': 'var(--accent-brand-hover)',
          'brand-muted': 'var(--accent-brand-muted)',
          'brand-ring': 'var(--accent-brand-ring)',
          green: 'var(--accent-green)',
          red: 'var(--accent-red)',
          blue: 'var(--accent-blue)',
          amber: 'var(--accent-amber)',
        },
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        inset: 'var(--shadow-inset)',
      },
      animation: {
        'in': 'fadeIn 0.3s ease-out',
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      typography: {
        DEFAULT: {
          css: {
            '--tw-prose-body': 'var(--text-primary)',
            '--tw-prose-headings': 'var(--text-primary)',
            '--tw-prose-links': 'var(--accent-green)',
            '--tw-prose-bold': 'var(--text-primary)',
            '--tw-prose-code': 'var(--accent-green)',
            '--tw-prose-pre-bg': 'var(--bg-code)',
            '--tw-prose-pre-code': 'var(--text-primary)',
            '--tw-prose-quotes': 'var(--text-secondary)',
            '--tw-prose-quote-borders': 'var(--border-strong)',
            '--tw-prose-th-borders': 'var(--border-subtle)',
            '--tw-prose-td-borders': 'var(--border-subtle)',
          },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};

export default config;
