import { siteConfig } from '@/lib/seo';

type JsonLdProps = { data: Record<string, unknown> | Record<string, unknown>[] };

export function JsonLd({ data }: JsonLdProps) {
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}

export const organizationSchema = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: siteConfig.name,
  url: siteConfig.url,
  logo: `${siteConfig.url}/icon-512.svg`,
  sameAs: [
    'https://twitter.com/alphasightai',
    'https://www.linkedin.com/company/alphasightai',
    'https://github.com/alphasightai',
  ],
  contactPoint: {
    '@type': 'ContactPoint',
    email: siteConfig.email,
    contactType: 'customer support',
    availableLanguage: ['en'],
  },
} as const;

export const websiteSchema = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: siteConfig.name,
  url: siteConfig.url,
  description: siteConfig.description,
  inLanguage: 'en-US',
  potentialAction: {
    '@type': 'SearchAction',
    target: `${siteConfig.url}/chat?q={search_term_string}`,
    'query-input': 'required name=search_term_string',
  },
} as const;

export const softwareApplicationSchema = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: siteConfig.name,
  applicationCategory: 'FinanceApplication',
  applicationSubCategory: 'Investment Research',
  operatingSystem: 'Web, iOS, Android',
  url: siteConfig.url,
  description: siteConfig.longDescription,
  offers: {
    '@type': 'Offer',
    price: '0',
    priceCurrency: 'USD',
    description: 'Free tier available; premium plans for advanced research.',
  },
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '4.8',
    ratingCount: '128',
    bestRating: '5',
    worstRating: '1',
  },
  featureList: [
    'AI-powered stock analysis',
    'Real-time market data',
    'Portfolio tracking',
    'Watchlist with alerts',
    'Daily market brief',
    'Streaming AI chat',
    'Sentiment analysis',
    'Fundamental and technical research',
  ],
  publisher: {
    '@type': 'Organization',
    name: siteConfig.name,
    url: siteConfig.url,
  },
} as const;

export const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'What is AlphaSight AI?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'AlphaSight AI is an AI-powered stock analysis workspace combining streaming LLM chat, real-time market data, portfolio tracking, and personalized daily briefs to help investors make better decisions.',
      },
    },
    {
      '@type': 'Question',
      name: 'Is AlphaSight AI free to use?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Yes, AlphaSight AI offers a free tier with core stock chat, watchlist, and portfolio features. Premium plans unlock deeper research, faster models, and advanced analytics.',
      },
    },
    {
      '@type': 'Question',
      name: 'Where does the market data come from?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Live quotes and historical data come from Yahoo Finance. AI commentary is generated by large language models (Mistral, Groq Llama) over fresh market context.',
      },
    },
    {
      '@type': 'Question',
      name: 'Does AlphaSight AI give financial advice?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'No. AlphaSight AI provides research, analysis, and information for educational purposes. It is not a registered investment advisor and does not provide personalized financial advice.',
      },
    },
    {
      '@type': 'Question',
      name: 'Is my data secure?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'AlphaSight AI uses Supabase with row-level security, HTTPS everywhere, secure HTTP-only auth cookies, and a strict Content Security Policy.',
      },
    },
  ],
} as const;
