import type { Metadata } from 'next';
import { buildMetadata, routeSeo, siteConfig } from '@/lib/seo';
import { LegalPage } from '@/components/seo/legal-page';

export const metadata: Metadata = buildMetadata(routeSeo.terms);

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="May 24, 2026">
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use of AlphaSight AI
        (the &quot;Service&quot;) operated by AlphaSight AI (&quot;we&quot;, &quot;us&quot;).
        By creating an account or using the Service you agree to these Terms. If you do not agree,
        do not use the Service.
      </p>

      <h2>1. Eligibility</h2>
      <p>You must be at least 16 years old (or the age of majority in your jurisdiction) and legally able to enter contracts. If you use the Service on behalf of an organization, you represent that you have authority to bind that organization.</p>

      <h2>2. Account</h2>
      <ul>
        <li>You are responsible for safeguarding your credentials and for all activity under your account.</li>
        <li>Notify us at <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a> of any unauthorized access.</li>
        <li>One person or legal entity may not maintain multiple free accounts to circumvent usage limits.</li>
      </ul>

      <h2>3. Acceptable use</h2>
      <p>You agree NOT to:</p>
      <ul>
        <li>Use the Service to violate any law or third-party right.</li>
        <li>Scrape, mirror, or reverse-engineer the Service or its data feeds.</li>
        <li>Resell, sub-license, or republish AI outputs or market data for commercial redistribution.</li>
        <li>Attempt to extract training data, system prompts, or proprietary model weights.</li>
        <li>Probe, attack, overload, or disrupt the Service or its infrastructure.</li>
        <li>Use the Service for high-frequency or automated trading without our written permission.</li>
        <li>Submit content that is illegal, defamatory, harassing, infringing, malicious, or violates anyone&apos;s privacy.</li>
      </ul>

      <h2>4. NOT FINANCIAL ADVICE</h2>
      <p><strong>AlphaSight AI is an informational and research tool. We are not a registered investment adviser, broker-dealer, financial planner, accountant, or tax professional in any jurisdiction. Nothing on the Service constitutes a recommendation, solicitation, or offer to buy or sell any security, derivative, or other financial instrument. AI outputs may be inaccurate, incomplete, or out of date. All investment decisions are made at your sole risk. Consult a licensed professional before making any financial decision. See our full <a href="/disclaimer">Disclaimer</a>.</strong></p>

      <h2>5. Market data</h2>
      <p>Market data is provided by third parties including Yahoo Finance and may be delayed, inaccurate, or unavailable. We do not guarantee its accuracy or timeliness and we are not liable for any loss arising from its use.</p>

      <h2>6. AI outputs</h2>
      <p>You may use AI outputs for personal research. Outputs are generated by stochastic models and may be wrong. You are responsible for verifying any output before acting on it. AI outputs are not subject to copyright when generated entirely by the model, but you retain rights to your own prompts.</p>

      <h2>7. Subscriptions and billing</h2>
      <ul>
        <li>Paid plans renew automatically until cancelled.</li>
        <li>You can cancel at any time; cancellations take effect at the end of the current billing period.</li>
        <li>Fees are non-refundable except where required by law or as expressly stated.</li>
        <li>We may change pricing with 30 days&apos; notice for existing subscribers.</li>
      </ul>

      <h2>8. Intellectual property</h2>
      <p>The Service, including all software, design, text, graphics, and trademarks, is owned by AlphaSight AI or its licensors and protected by intellectual property laws. We grant you a limited, revocable, non-exclusive, non-transferable license to access the Service for personal or internal business use.</p>

      <h2>9. Termination</h2>
      <p>We may suspend or terminate your access at any time for breach of these Terms, illegal activity, or risk to the Service or other users. You may delete your account at any time from settings.</p>

      <h2>10. Disclaimers</h2>
      <p>The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, express or implied, including merchantability, fitness for a particular purpose, non-infringement, and any warranty arising from course of dealing or trade usage. We do not warrant that the Service will be uninterrupted, timely, secure, or error-free.</p>

      <h2>11. Limitation of liability</h2>
      <p>To the maximum extent permitted by law, AlphaSight AI and its affiliates will not be liable for any indirect, incidental, special, consequential, punitive, or exemplary damages, or for lost profits, lost revenues, or lost data, even if advised of the possibility. Our total aggregate liability arising from or related to the Service will not exceed the greater of (a) the fees you paid us in the 12 months prior to the claim, or (b) US$100.</p>

      <h2>12. Indemnification</h2>
      <p>You agree to indemnify and hold harmless AlphaSight AI from any claim arising out of your use of the Service, your content, or your violation of these Terms.</p>

      <h2>13. Governing law</h2>
      <p>These Terms are governed by the laws of the State of Delaware, USA, excluding its conflict-of-laws rules. Disputes will be resolved by binding arbitration on an individual basis under JAMS rules, except that either party may bring claims in small-claims court. You waive any right to a jury trial or class action.</p>

      <h2>14. Changes</h2>
      <p>We may update these Terms from time to time. Material changes will be posted on this page with an updated effective date and, where required, notified by email.</p>

      <h2>15. Contact</h2>
      <p>AlphaSight AI · <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a></p>
    </LegalPage>
  );
}
