import {
  BookOpen,
  Gauge,
  Globe2,
  Mic,
  Newspaper,
  Scale,
  ShieldAlert,
  Sparkles,
  Swords,
  Target,
} from 'lucide-react';
import { AISectionCard } from '../_components/ai-section-card';

interface AnalysisPageProps {
  params: Promise<{ symbol: string }>;
}

const SECTIONS = [
  {
    title: 'AI Summary',
    topic: 'summary',
    description: 'Plain-English business summary, growth drivers and outlook.',
    icon: Sparkles,
  },
  {
    title: 'AlphaScore',
    topic: 'alpha-score',
    description:
      'Composite scoring across Growth, Value, Quality, Risk, Momentum, Management.',
    icon: Gauge,
  },
  {
    title: 'Pros & Cons',
    topic: 'pros-cons',
    description: 'Bull and bear case at a glance.',
    icon: Scale,
  },
  {
    title: 'Fair Value Engine',
    topic: 'fair-value',
    description:
      'AI-estimated intrinsic value vs current price with margin of safety.',
    icon: Target,
  },
  {
    title: 'Investment Thesis',
    topic: 'thesis',
    description: 'Bull case, bear case and 3-year / 5-year outlook.',
    icon: BookOpen,
  },
  {
    title: 'Earnings Analyzer',
    topic: 'earnings',
    description: 'Concall, guidance, sentiment and management confidence.',
    icon: Mic,
  },
  {
    title: 'Competitor Intelligence',
    topic: 'competitors',
    description: 'Best margins, fastest growth, AI Winner across peers.',
    icon: Swords,
  },
  {
    title: 'News Impact',
    topic: 'news-impact',
    description:
      'Recent news scored for price-impact direction and magnitude.',
    icon: Newspaper,
  },
  {
    title: 'Risk Center',
    topic: 'risk',
    description:
      'Regulatory, industry, debt, management and governance risks.',
    icon: ShieldAlert,
  },
  {
    title: 'Geopolitics Impact',
    topic: 'geopolitics',
    description:
      "How global policy, trade tensions and conflicts affect this company's earnings.",
    icon: Globe2,
  },
] as const;

export default async function AnalysisPage({ params }: AnalysisPageProps) {
  const { symbol: raw } = await params;
  const symbol = decodeURIComponent(raw || '').toUpperCase();

  return (
    <div className="flex flex-col gap-5">
      <header className="flex flex-col gap-1">
        <h2 className="text-lg font-semibold text-primary sm:text-xl">
          AI Insights
        </h2>
        <p className="text-sm text-secondary">
          Generated by Cerebras AI across business fundamentals, peers and
          macro context.
        </p>
      </header>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        {SECTIONS.map((s) => (
          <AISectionCard
            key={s.topic}
            symbol={symbol}
            topic={s.topic}
            title={s.title}
            description={s.description}
            icon={s.icon}
          />
        ))}
      </div>
    </div>
  );
}
