import type { Metadata } from 'next';
import { buildMetadata, routeSeo, siteConfig } from '@/lib/seo';
import { LegalPage } from '@/components/seo/legal-page';

export const metadata: Metadata = buildMetadata(routeSeo.disclaimer);

export default function DisclaimerPage() {
  return (
    <LegalPage title="Financial Disclaimer" updated="May 24, 2026">
      <p><strong>Read this carefully before using AlphaSight AI.</strong></p>

      <h2>1. Not financial advice</h2>
      <p>AlphaSight AI provides AI-generated research, news summaries, market data, charts, and analytical tools for informational and educational purposes only. Nothing on the platform constitutes financial, investment, legal, tax, or accounting advice. We are not a registered investment adviser, broker-dealer, financial planner, or licensed professional in any jurisdiction.</p>

      <h2>2. No recommendation</h2>
      <p>References to specific securities, indices, ETFs, cryptocurrencies, or other financial instruments are not recommendations or solicitations to buy, sell, or hold. AI commentary, scores, sentiment analysis, and rankings are not personalized to your circumstances and should not be relied upon as the sole basis for any investment decision.</p>

      <h2>3. AI limitations</h2>
      <p>Outputs are generated by stochastic large language models. They can be wrong, outdated, hallucinated, or biased. The platform may misinterpret news, misattribute statements, or omit material information. Always verify with primary sources (issuer filings, exchange announcements, regulatory disclosures) before acting.</p>

      <h2>4. Market data</h2>
      <p>Quotes, financials, and fundamentals come from third parties such as Yahoo Finance. Data may be delayed by 15 minutes or more, may contain errors, and may be unavailable due to provider outages. We do not guarantee accuracy, completeness, or timeliness.</p>

      <h2>5. Past performance</h2>
      <p>Past performance does not guarantee future results. Backtests, simulated returns, and historical charts are hypothetical and have inherent limitations. Actual returns will differ.</p>

      <h2>6. Risk of loss</h2>
      <p>Trading and investing involve substantial risk including the possible loss of principal. You should not invest money you cannot afford to lose. Leverage, margin, derivatives, and short selling amplify both gains and losses. Consult a licensed professional and consider your own financial situation, objectives, and risk tolerance before investing.</p>

      <h2>7. No fiduciary duty</h2>
      <p>Use of the Service does not create any fiduciary, advisory, or professional relationship between you and AlphaSight AI.</p>

      <h2>8. Forward-looking statements</h2>
      <p>Content may include forward-looking statements based on current expectations. Actual events may differ materially. We undertake no obligation to update such statements.</p>

      <h2>9. Affiliates and conflicts</h2>
      <p>We may receive compensation from brokerages or data providers through referral programs. Such arrangements never influence editorial or AI output.</p>

      <h2>10. Jurisdictional notes</h2>
      <p>Some content may not be appropriate or available in your jurisdiction. You are responsible for compliance with all local laws including securities, tax, and anti-money-laundering regulations.</p>

      <h2>11. Contact</h2>
      <p>Questions: <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a></p>
    </LegalPage>
  );
}
